services:
  - type: web
    name: my-php-site
    runtime: php
    plan: free
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:10000 -t ."

    envVars:
      - key: DATABASE_HOST
        value: ep-morning-king-a4zj91ou-pooler.us-east-1.aws.neon.tech

      - key: DATABASE_NAME
        value: neondb

      - key: DATABASE_USER
        value: neondb_owner

      - key: DATABASE_PASSWORD
        value: npg_PT2jbzHiCn9t

      - key: DATABASE_PORT
        value: 5432










    
