services:
  - type: web
    name: php-neon-app
    plan: free
    env:
      DATABASE_HOST: ep-morning-king-a4zj91ou-pooler.us-east-1.aws.neon.tech
      DATABASE_NAME: neondb
      DATABASE_USER: neondb_owner
      DATABASE_PASSWORD: npg_PT2jbzHiCn9t
      DATABASE_PORT: 5432
    dockerfilePath: ./Dockerfile

    
